#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ShopOnline")]
	public partial class shoponlineDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertShop_Image(Shop_Image instance);
    partial void UpdateShop_Image(Shop_Image instance);
    partial void DeleteShop_Image(Shop_Image instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertShop_Item(Shop_Item instance);
    partial void UpdateShop_Item(Shop_Item instance);
    partial void DeleteShop_Item(Shop_Item instance);
    partial void InsertShop_New(Shop_New instance);
    partial void UpdateShop_New(Shop_New instance);
    partial void DeleteShop_New(Shop_New instance);
    partial void InsertGroupMember(GroupMember instance);
    partial void UpdateGroupMember(GroupMember instance);
    partial void DeleteGroupMember(GroupMember instance);
    partial void InsertGroup(Group instance);
    partial void UpdateGroup(Group instance);
    partial void DeleteGroup(Group instance);
    #endregion
		
		public shoponlineDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ShopOnlineConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public shoponlineDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public shoponlineDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public shoponlineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public shoponlineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Shop_Image> Shop_Images
		{
			get
			{
				return this.GetTable<Shop_Image>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Shop_Item> Shop_Items
		{
			get
			{
				return this.GetTable<Shop_Item>();
			}
		}
		
		public System.Data.Linq.Table<Shop_New> Shop_News
		{
			get
			{
				return this.GetTable<Shop_New>();
			}
		}
		
		public System.Data.Linq.Table<GroupMember> GroupMembers
		{
			get
			{
				return this.GetTable<GroupMember>();
			}
		}
		
		public System.Data.Linq.Table<Group> Groups
		{
			get
			{
				return this.GetTable<Group>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shop_Images")]
	public partial class Shop_Image : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Shop_Image_Id;
		
		private long _User_Id;
		
		private string _Image_Title;
		
		private string _Image_Path;
		
		private bool _Is_For_Home_Page_Slider;
		
		private System.DateTime _Created_On;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnShop_Image_IdChanging(long value);
    partial void OnShop_Image_IdChanged();
    partial void OnUser_IdChanging(long value);
    partial void OnUser_IdChanged();
    partial void OnImage_TitleChanging(string value);
    partial void OnImage_TitleChanged();
    partial void OnImage_PathChanging(string value);
    partial void OnImage_PathChanged();
    partial void OnIs_For_Home_Page_SliderChanging(bool value);
    partial void OnIs_For_Home_Page_SliderChanged();
    partial void OnCreated_OnChanging(System.DateTime value);
    partial void OnCreated_OnChanged();
    #endregion
		
		public Shop_Image()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shop_Image_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Shop_Image_Id
		{
			get
			{
				return this._Shop_Image_Id;
			}
			set
			{
				if ((this._Shop_Image_Id != value))
				{
					this.OnShop_Image_IdChanging(value);
					this.SendPropertyChanging();
					this._Shop_Image_Id = value;
					this.SendPropertyChanged("Shop_Image_Id");
					this.OnShop_Image_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="BigInt NOT NULL")]
		public long User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_Title", DbType="VarChar(250)")]
		public string Image_Title
		{
			get
			{
				return this._Image_Title;
			}
			set
			{
				if ((this._Image_Title != value))
				{
					this.OnImage_TitleChanging(value);
					this.SendPropertyChanging();
					this._Image_Title = value;
					this.SendPropertyChanged("Image_Title");
					this.OnImage_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_Path", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string Image_Path
		{
			get
			{
				return this._Image_Path;
			}
			set
			{
				if ((this._Image_Path != value))
				{
					this.OnImage_PathChanging(value);
					this.SendPropertyChanging();
					this._Image_Path = value;
					this.SendPropertyChanged("Image_Path");
					this.OnImage_PathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_For_Home_Page_Slider", DbType="Bit NOT NULL")]
		public bool Is_For_Home_Page_Slider
		{
			get
			{
				return this._Is_For_Home_Page_Slider;
			}
			set
			{
				if ((this._Is_For_Home_Page_Slider != value))
				{
					this.OnIs_For_Home_Page_SliderChanging(value);
					this.SendPropertyChanging();
					this._Is_For_Home_Page_Slider = value;
					this.SendPropertyChanged("Is_For_Home_Page_Slider");
					this.OnIs_For_Home_Page_SliderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_On", DbType="DateTime NOT NULL")]
		public System.DateTime Created_On
		{
			get
			{
				return this._Created_On;
			}
			set
			{
				if ((this._Created_On != value))
				{
					this.OnCreated_OnChanging(value);
					this.SendPropertyChanging();
					this._Created_On = value;
					this.SendPropertyChanged("Created_On");
					this.OnCreated_OnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _UserId;
		
		private int _UserRoleId;
		
		private string _UserLoginName;
		
		private string _UserPassword;
		
		private string _UserFirstName;
		
		private string _UserLastName;
		
		private string _UserContactNumber;
		
		private int _UserStatus;
		
		private string _Contact_Email;
		
		private string _ProfilePhoto;
		
		private string _ShopName;
		
		private string _ShopCountry;
		
		private string _ShopCity;
		
		private string _ShopAddress;
		
		private string _ShopMapUrl;
		
		private string _ShopPhoto;
		
		private string _ShopDescription;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _Gender;
		
		private bool _Is_ShopCreated;
		
		private System.Nullable<System.DateTime> _Shop_Last_Updated_On;
		
		private System.Nullable<System.DateTime> _Created_On;
		
		private System.Nullable<System.DateTime> _Last_Updated_On;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(long value);
    partial void OnUserIdChanged();
    partial void OnUserRoleIdChanging(int value);
    partial void OnUserRoleIdChanged();
    partial void OnUserLoginNameChanging(string value);
    partial void OnUserLoginNameChanged();
    partial void OnUserPasswordChanging(string value);
    partial void OnUserPasswordChanged();
    partial void OnUserFirstNameChanging(string value);
    partial void OnUserFirstNameChanged();
    partial void OnUserLastNameChanging(string value);
    partial void OnUserLastNameChanged();
    partial void OnUserContactNumberChanging(string value);
    partial void OnUserContactNumberChanged();
    partial void OnUserStatusChanging(int value);
    partial void OnUserStatusChanged();
    partial void OnContact_EmailChanging(string value);
    partial void OnContact_EmailChanged();
    partial void OnProfilePhotoChanging(string value);
    partial void OnProfilePhotoChanged();
    partial void OnShopNameChanging(string value);
    partial void OnShopNameChanged();
    partial void OnShopCountryChanging(string value);
    partial void OnShopCountryChanged();
    partial void OnShopCityChanging(string value);
    partial void OnShopCityChanged();
    partial void OnShopAddressChanging(string value);
    partial void OnShopAddressChanged();
    partial void OnShopMapUrlChanging(string value);
    partial void OnShopMapUrlChanged();
    partial void OnShopPhotoChanging(string value);
    partial void OnShopPhotoChanged();
    partial void OnShopDescriptionChanging(string value);
    partial void OnShopDescriptionChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnIs_ShopCreatedChanging(bool value);
    partial void OnIs_ShopCreatedChanged();
    partial void OnShop_Last_Updated_OnChanging(System.Nullable<System.DateTime> value);
    partial void OnShop_Last_Updated_OnChanged();
    partial void OnCreated_OnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreated_OnChanged();
    partial void OnLast_Updated_OnChanging(System.Nullable<System.DateTime> value);
    partial void OnLast_Updated_OnChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRoleId", DbType="Int NOT NULL")]
		public int UserRoleId
		{
			get
			{
				return this._UserRoleId;
			}
			set
			{
				if ((this._UserRoleId != value))
				{
					this.OnUserRoleIdChanging(value);
					this.SendPropertyChanging();
					this._UserRoleId = value;
					this.SendPropertyChanged("UserRoleId");
					this.OnUserRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLoginName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string UserLoginName
		{
			get
			{
				return this._UserLoginName;
			}
			set
			{
				if ((this._UserLoginName != value))
				{
					this.OnUserLoginNameChanging(value);
					this.SendPropertyChanging();
					this._UserLoginName = value;
					this.SendPropertyChanged("UserLoginName");
					this.OnUserLoginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPassword", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UserPassword
		{
			get
			{
				return this._UserPassword;
			}
			set
			{
				if ((this._UserPassword != value))
				{
					this.OnUserPasswordChanging(value);
					this.SendPropertyChanging();
					this._UserPassword = value;
					this.SendPropertyChanged("UserPassword");
					this.OnUserPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFirstName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UserFirstName
		{
			get
			{
				return this._UserFirstName;
			}
			set
			{
				if ((this._UserFirstName != value))
				{
					this.OnUserFirstNameChanging(value);
					this.SendPropertyChanging();
					this._UserFirstName = value;
					this.SendPropertyChanged("UserFirstName");
					this.OnUserFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLastName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UserLastName
		{
			get
			{
				return this._UserLastName;
			}
			set
			{
				if ((this._UserLastName != value))
				{
					this.OnUserLastNameChanging(value);
					this.SendPropertyChanging();
					this._UserLastName = value;
					this.SendPropertyChanged("UserLastName");
					this.OnUserLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserContactNumber", DbType="VarChar(20)")]
		public string UserContactNumber
		{
			get
			{
				return this._UserContactNumber;
			}
			set
			{
				if ((this._UserContactNumber != value))
				{
					this.OnUserContactNumberChanging(value);
					this.SendPropertyChanging();
					this._UserContactNumber = value;
					this.SendPropertyChanged("UserContactNumber");
					this.OnUserContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserStatus", DbType="Int NOT NULL")]
		public int UserStatus
		{
			get
			{
				return this._UserStatus;
			}
			set
			{
				if ((this._UserStatus != value))
				{
					this.OnUserStatusChanging(value);
					this.SendPropertyChanging();
					this._UserStatus = value;
					this.SendPropertyChanged("UserStatus");
					this.OnUserStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact_Email", DbType="VarChar(250)")]
		public string Contact_Email
		{
			get
			{
				return this._Contact_Email;
			}
			set
			{
				if ((this._Contact_Email != value))
				{
					this.OnContact_EmailChanging(value);
					this.SendPropertyChanging();
					this._Contact_Email = value;
					this.SendPropertyChanged("Contact_Email");
					this.OnContact_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePhoto", DbType="VarChar(250)")]
		public string ProfilePhoto
		{
			get
			{
				return this._ProfilePhoto;
			}
			set
			{
				if ((this._ProfilePhoto != value))
				{
					this.OnProfilePhotoChanging(value);
					this.SendPropertyChanging();
					this._ProfilePhoto = value;
					this.SendPropertyChanged("ProfilePhoto");
					this.OnProfilePhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopName", DbType="NVarChar(100)")]
		public string ShopName
		{
			get
			{
				return this._ShopName;
			}
			set
			{
				if ((this._ShopName != value))
				{
					this.OnShopNameChanging(value);
					this.SendPropertyChanging();
					this._ShopName = value;
					this.SendPropertyChanged("ShopName");
					this.OnShopNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopCountry", DbType="NVarChar(50)")]
		public string ShopCountry
		{
			get
			{
				return this._ShopCountry;
			}
			set
			{
				if ((this._ShopCountry != value))
				{
					this.OnShopCountryChanging(value);
					this.SendPropertyChanging();
					this._ShopCountry = value;
					this.SendPropertyChanged("ShopCountry");
					this.OnShopCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopCity", DbType="NVarChar(50)")]
		public string ShopCity
		{
			get
			{
				return this._ShopCity;
			}
			set
			{
				if ((this._ShopCity != value))
				{
					this.OnShopCityChanging(value);
					this.SendPropertyChanging();
					this._ShopCity = value;
					this.SendPropertyChanged("ShopCity");
					this.OnShopCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopAddress", DbType="NVarChar(500)")]
		public string ShopAddress
		{
			get
			{
				return this._ShopAddress;
			}
			set
			{
				if ((this._ShopAddress != value))
				{
					this.OnShopAddressChanging(value);
					this.SendPropertyChanging();
					this._ShopAddress = value;
					this.SendPropertyChanged("ShopAddress");
					this.OnShopAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopMapUrl", DbType="NVarChar(1000)")]
		public string ShopMapUrl
		{
			get
			{
				return this._ShopMapUrl;
			}
			set
			{
				if ((this._ShopMapUrl != value))
				{
					this.OnShopMapUrlChanging(value);
					this.SendPropertyChanging();
					this._ShopMapUrl = value;
					this.SendPropertyChanged("ShopMapUrl");
					this.OnShopMapUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopPhoto", DbType="NVarChar(250)")]
		public string ShopPhoto
		{
			get
			{
				return this._ShopPhoto;
			}
			set
			{
				if ((this._ShopPhoto != value))
				{
					this.OnShopPhotoChanging(value);
					this.SendPropertyChanging();
					this._ShopPhoto = value;
					this.SendPropertyChanged("ShopPhoto");
					this.OnShopPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopDescription", DbType="NVarChar(2000)")]
		public string ShopDescription
		{
			get
			{
				return this._ShopDescription;
			}
			set
			{
				if ((this._ShopDescription != value))
				{
					this.OnShopDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ShopDescription = value;
					this.SendPropertyChanged("ShopDescription");
					this.OnShopDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(10)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_ShopCreated", DbType="Bit NOT NULL")]
		public bool Is_ShopCreated
		{
			get
			{
				return this._Is_ShopCreated;
			}
			set
			{
				if ((this._Is_ShopCreated != value))
				{
					this.OnIs_ShopCreatedChanging(value);
					this.SendPropertyChanging();
					this._Is_ShopCreated = value;
					this.SendPropertyChanged("Is_ShopCreated");
					this.OnIs_ShopCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shop_Last_Updated_On", DbType="DateTime")]
		public System.Nullable<System.DateTime> Shop_Last_Updated_On
		{
			get
			{
				return this._Shop_Last_Updated_On;
			}
			set
			{
				if ((this._Shop_Last_Updated_On != value))
				{
					this.OnShop_Last_Updated_OnChanging(value);
					this.SendPropertyChanging();
					this._Shop_Last_Updated_On = value;
					this.SendPropertyChanged("Shop_Last_Updated_On");
					this.OnShop_Last_Updated_OnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_On", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created_On
		{
			get
			{
				return this._Created_On;
			}
			set
			{
				if ((this._Created_On != value))
				{
					this.OnCreated_OnChanging(value);
					this.SendPropertyChanging();
					this._Created_On = value;
					this.SendPropertyChanged("Created_On");
					this.OnCreated_OnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Updated_On", DbType="DateTime")]
		public System.Nullable<System.DateTime> Last_Updated_On
		{
			get
			{
				return this._Last_Updated_On;
			}
			set
			{
				if ((this._Last_Updated_On != value))
				{
					this.OnLast_Updated_OnChanging(value);
					this.SendPropertyChanging();
					this._Last_Updated_On = value;
					this.SendPropertyChanged("Last_Updated_On");
					this.OnLast_Updated_OnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shop_Items")]
	public partial class Shop_Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ItemId;
		
		private long _User_Id;
		
		private string _ItemName;
		
		private string _ItemCompany;
		
		private string _ItemBrand;
		
		private string _ItemPrice;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<System.DateTime> _Created_On;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItemIdChanging(long value);
    partial void OnItemIdChanged();
    partial void OnUser_IdChanging(long value);
    partial void OnUser_IdChanged();
    partial void OnItemNameChanging(string value);
    partial void OnItemNameChanged();
    partial void OnItemCompanyChanging(string value);
    partial void OnItemCompanyChanged();
    partial void OnItemBrandChanging(string value);
    partial void OnItemBrandChanged();
    partial void OnItemPriceChanging(string value);
    partial void OnItemPriceChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnCreated_OnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreated_OnChanged();
    #endregion
		
		public Shop_Item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ItemId
		{
			get
			{
				return this._ItemId;
			}
			set
			{
				if ((this._ItemId != value))
				{
					this.OnItemIdChanging(value);
					this.SendPropertyChanging();
					this._ItemId = value;
					this.SendPropertyChanged("ItemId");
					this.OnItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="BigInt NOT NULL")]
		public long User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(50)")]
		public string ItemName
		{
			get
			{
				return this._ItemName;
			}
			set
			{
				if ((this._ItemName != value))
				{
					this.OnItemNameChanging(value);
					this.SendPropertyChanging();
					this._ItemName = value;
					this.SendPropertyChanged("ItemName");
					this.OnItemNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCompany", DbType="NVarChar(50)")]
		public string ItemCompany
		{
			get
			{
				return this._ItemCompany;
			}
			set
			{
				if ((this._ItemCompany != value))
				{
					this.OnItemCompanyChanging(value);
					this.SendPropertyChanging();
					this._ItemCompany = value;
					this.SendPropertyChanged("ItemCompany");
					this.OnItemCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemBrand", DbType="NVarChar(50)")]
		public string ItemBrand
		{
			get
			{
				return this._ItemBrand;
			}
			set
			{
				if ((this._ItemBrand != value))
				{
					this.OnItemBrandChanging(value);
					this.SendPropertyChanging();
					this._ItemBrand = value;
					this.SendPropertyChanged("ItemBrand");
					this.OnItemBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemPrice", DbType="VarChar(20)")]
		public string ItemPrice
		{
			get
			{
				return this._ItemPrice;
			}
			set
			{
				if ((this._ItemPrice != value))
				{
					this.OnItemPriceChanging(value);
					this.SendPropertyChanging();
					this._ItemPrice = value;
					this.SendPropertyChanged("ItemPrice");
					this.OnItemPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_On", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created_On
		{
			get
			{
				return this._Created_On;
			}
			set
			{
				if ((this._Created_On != value))
				{
					this.OnCreated_OnChanging(value);
					this.SendPropertyChanging();
					this._Created_On = value;
					this.SendPropertyChanged("Created_On");
					this.OnCreated_OnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shop_News")]
	public partial class Shop_New : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _NewsId;
		
		private long _User_Id;
		
		private string _News_HeadLine;
		
		private string _News_Detail;
		
		private System.Nullable<System.DateTime> _Created_On;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNewsIdChanging(long value);
    partial void OnNewsIdChanged();
    partial void OnUser_IdChanging(long value);
    partial void OnUser_IdChanged();
    partial void OnNews_HeadLineChanging(string value);
    partial void OnNews_HeadLineChanged();
    partial void OnNews_DetailChanging(string value);
    partial void OnNews_DetailChanged();
    partial void OnCreated_OnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreated_OnChanged();
    #endregion
		
		public Shop_New()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long NewsId
		{
			get
			{
				return this._NewsId;
			}
			set
			{
				if ((this._NewsId != value))
				{
					this.OnNewsIdChanging(value);
					this.SendPropertyChanging();
					this._NewsId = value;
					this.SendPropertyChanged("NewsId");
					this.OnNewsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="BigInt NOT NULL")]
		public long User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_News_HeadLine", DbType="NVarChar(50)")]
		public string News_HeadLine
		{
			get
			{
				return this._News_HeadLine;
			}
			set
			{
				if ((this._News_HeadLine != value))
				{
					this.OnNews_HeadLineChanging(value);
					this.SendPropertyChanging();
					this._News_HeadLine = value;
					this.SendPropertyChanged("News_HeadLine");
					this.OnNews_HeadLineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_News_Detail", DbType="NVarChar(500)")]
		public string News_Detail
		{
			get
			{
				return this._News_Detail;
			}
			set
			{
				if ((this._News_Detail != value))
				{
					this.OnNews_DetailChanging(value);
					this.SendPropertyChanging();
					this._News_Detail = value;
					this.SendPropertyChanged("News_Detail");
					this.OnNews_DetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_On", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created_On
		{
			get
			{
				return this._Created_On;
			}
			set
			{
				if ((this._Created_On != value))
				{
					this.OnCreated_OnChanging(value);
					this.SendPropertyChanging();
					this._Created_On = value;
					this.SendPropertyChanged("Created_On");
					this.OnCreated_OnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GroupMembers")]
	public partial class GroupMember : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _GroupMemberId;
		
		private System.Nullable<long> _Group_Id;
		
		private System.Nullable<long> _User_Id;
		
		private System.Nullable<int> _MemberRole;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _AddBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroupMemberIdChanging(long value);
    partial void OnGroupMemberIdChanged();
    partial void OnGroup_IdChanging(System.Nullable<long> value);
    partial void OnGroup_IdChanged();
    partial void OnUser_IdChanging(System.Nullable<long> value);
    partial void OnUser_IdChanged();
    partial void OnMemberRoleChanging(System.Nullable<int> value);
    partial void OnMemberRoleChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnAddByChanging(System.Nullable<long> value);
    partial void OnAddByChanged();
    #endregion
		
		public GroupMember()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupMemberId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long GroupMemberId
		{
			get
			{
				return this._GroupMemberId;
			}
			set
			{
				if ((this._GroupMemberId != value))
				{
					this.OnGroupMemberIdChanging(value);
					this.SendPropertyChanging();
					this._GroupMemberId = value;
					this.SendPropertyChanged("GroupMemberId");
					this.OnGroupMemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group_Id", DbType="BigInt")]
		public System.Nullable<long> Group_Id
		{
			get
			{
				return this._Group_Id;
			}
			set
			{
				if ((this._Group_Id != value))
				{
					this.OnGroup_IdChanging(value);
					this.SendPropertyChanging();
					this._Group_Id = value;
					this.SendPropertyChanged("Group_Id");
					this.OnGroup_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="BigInt")]
		public System.Nullable<long> User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberRole", DbType="Int")]
		public System.Nullable<int> MemberRole
		{
			get
			{
				return this._MemberRole;
			}
			set
			{
				if ((this._MemberRole != value))
				{
					this.OnMemberRoleChanging(value);
					this.SendPropertyChanging();
					this._MemberRole = value;
					this.SendPropertyChanged("MemberRole");
					this.OnMemberRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddBy", DbType="BigInt")]
		public System.Nullable<long> AddBy
		{
			get
			{
				return this._AddBy;
			}
			set
			{
				if ((this._AddBy != value))
				{
					this.OnAddByChanging(value);
					this.SendPropertyChanging();
					this._AddBy = value;
					this.SendPropertyChanged("AddBy");
					this.OnAddByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Groups")]
	public partial class Group : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _GroupId;
		
		private long _User_Id;
		
		private string _Name;
		
		private string _GroupDescription;
		
		private string _GroupType;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroupIdChanging(long value);
    partial void OnGroupIdChanged();
    partial void OnUser_IdChanging(long value);
    partial void OnUser_IdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnGroupDescriptionChanging(string value);
    partial void OnGroupDescriptionChanged();
    partial void OnGroupTypeChanging(string value);
    partial void OnGroupTypeChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    #endregion
		
		public Group()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this.OnGroupIdChanging(value);
					this.SendPropertyChanging();
					this._GroupId = value;
					this.SendPropertyChanged("GroupId");
					this.OnGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="BigInt NOT NULL")]
		public long User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(70)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupDescription", DbType="NVarChar(500)")]
		public string GroupDescription
		{
			get
			{
				return this._GroupDescription;
			}
			set
			{
				if ((this._GroupDescription != value))
				{
					this.OnGroupDescriptionChanging(value);
					this.SendPropertyChanging();
					this._GroupDescription = value;
					this.SendPropertyChanged("GroupDescription");
					this.OnGroupDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupType", DbType="NVarChar(10)")]
		public string GroupType
		{
			get
			{
				return this._GroupType;
			}
			set
			{
				if ((this._GroupType != value))
				{
					this.OnGroupTypeChanging(value);
					this.SendPropertyChanging();
					this._GroupType = value;
					this.SendPropertyChanged("GroupType");
					this.OnGroupTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
